[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Proxy del front a las funciones
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
