[build]
  command = "npm run build"
  publish = ".next"

[plugins]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://mentalgym-pro.onrender.com/api/:splat"
  status = 200
  force = true
